# Generated by Django 6.0.3 on 2026-04-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_landlord_property_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landmarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
