# Generated by Django 6.0.3 on 2026-04-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_landmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], default='rent', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='property_category',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('townhouse', 'Townhouse'), ('land', 'Land'), ('commercial', 'Commercial'), ('student', 'Student Accommodation'), ('shortstay', 'Short Stay')], default='house', max_length=20),
        ),
    ]
