# Generated by Django 6.0.3 on 2026-05-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_created_at_message_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
    ]
